theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: spooon.org
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/logo.png"
  debug:
     productionUrl: "https://www.spooon.org/"